/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chess_game.ui;
import static chess_game.lib.Chess_Game.Board_UI;
import chess_game.lib.Moves;
import static chess_game.lib.Moves.show_moves;
/**
 *
 * @author Raid Nahi
 */
 public  class Board extends javax.swing.JFrame {

    /**
     * Creates new form Board
     */
    public Board() {
        initComponents();
        
        Board_UI.put("11", square_1_1);
        Board_UI.put("12", square_1_2);
        Board_UI.put("13", square_1_3);
        Board_UI.put("14", square_1_4);
        Board_UI.put("15", square_1_5);
        Board_UI.put("16", square_1_6);
        Board_UI.put("17", square_1_7);
        Board_UI.put("18", square_1_8);
        
        Board_UI.put("21", square_2_1);
        Board_UI.put("22", square_2_2);
        Board_UI.put("23", square_2_3);
        Board_UI.put("24", square_2_4);
        Board_UI.put("25", square_2_5);
        Board_UI.put("26", square_2_6);
        Board_UI.put("27", square_2_7);
        Board_UI.put("28", square_2_8);
 
        
        Board_UI.put("31", square_3_1);
        Board_UI.put("32", square_3_2);
        Board_UI.put("33", square_3_3);
        Board_UI.put("34", square_3_4);
        Board_UI.put("35", square_3_5);
        Board_UI.put("36", square_3_6);
        Board_UI.put("37", square_3_7);
        Board_UI.put("38", square_3_8);
        
        Board_UI.put("41", square_4_1);
        Board_UI.put("42", square_4_2);
        Board_UI.put("43", square_4_3);
        Board_UI.put("44", square_4_4);
        Board_UI.put("45", square_4_5);
        Board_UI.put("46", square_4_6);
        Board_UI.put("47", square_4_7);
        Board_UI.put("48", square_4_8);
        
        Board_UI.put("51", square_5_1);
        Board_UI.put("52", square_5_2);
        Board_UI.put("53", square_5_3);
        Board_UI.put("54", square_5_4);
        Board_UI.put("55", square_5_5);
        Board_UI.put("56", square_5_6);
        Board_UI.put("57", square_5_7);
        Board_UI.put("58", square_5_8);
        
        Board_UI.put("61", square_6_1);
        Board_UI.put("62", square_6_2);
        Board_UI.put("63", square_6_3);
        Board_UI.put("64", square_6_4);
        Board_UI.put("65", square_6_5);
        Board_UI.put("66", square_6_6);
        Board_UI.put("67", square_6_7);
        Board_UI.put("68", square_6_8);
        
        Board_UI.put("71", square_7_1);
        Board_UI.put("72", square_7_2);
        Board_UI.put("73", square_7_3);
        Board_UI.put("74", square_7_4);
        Board_UI.put("75", square_7_5);
        Board_UI.put("76", square_7_6);
        Board_UI.put("77", square_7_7);
        Board_UI.put("78", square_7_8);
        
        Board_UI.put("81", square_8_1);
        Board_UI.put("82", square_8_2);
        Board_UI.put("83", square_8_3);
        Board_UI.put("84", square_8_4);
        Board_UI.put("85", square_8_5);
        Board_UI.put("86", square_8_6);
        Board_UI.put("87", square_8_7);
        Board_UI.put("88", square_8_8);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        square_1_2 = new javax.swing.JButton();
        square_1_1 = new javax.swing.JButton();
        square_1_4 = new javax.swing.JButton();
        square_1_3 = new javax.swing.JButton();
        square_1_6 = new javax.swing.JButton();
        square_1_5 = new javax.swing.JButton();
        square_1_8 = new javax.swing.JButton();
        square_1_7 = new javax.swing.JButton();
        square_2_2 = new javax.swing.JButton();
        square_2_1 = new javax.swing.JButton();
        square_2_4 = new javax.swing.JButton();
        square_2_3 = new javax.swing.JButton();
        square_2_6 = new javax.swing.JButton();
        square_2_5 = new javax.swing.JButton();
        square_2_8 = new javax.swing.JButton();
        square_2_7 = new javax.swing.JButton();
        square_3_2 = new javax.swing.JButton();
        square_3_1 = new javax.swing.JButton();
        square_3_4 = new javax.swing.JButton();
        square_3_3 = new javax.swing.JButton();
        square_3_6 = new javax.swing.JButton();
        square_3_5 = new javax.swing.JButton();
        square_3_8 = new javax.swing.JButton();
        square_3_7 = new javax.swing.JButton();
        square_4_2 = new javax.swing.JButton();
        square_4_1 = new javax.swing.JButton();
        square_4_4 = new javax.swing.JButton();
        square_4_3 = new javax.swing.JButton();
        square_4_6 = new javax.swing.JButton();
        square_4_5 = new javax.swing.JButton();
        square_4_8 = new javax.swing.JButton();
        square_4_7 = new javax.swing.JButton();
        square_5_2 = new javax.swing.JButton();
        square_5_1 = new javax.swing.JButton();
        square_5_4 = new javax.swing.JButton();
        square_5_3 = new javax.swing.JButton();
        square_5_6 = new javax.swing.JButton();
        square_5_5 = new javax.swing.JButton();
        square_5_8 = new javax.swing.JButton();
        square_5_7 = new javax.swing.JButton();
        square_6_2 = new javax.swing.JButton();
        square_6_1 = new javax.swing.JButton();
        square_6_4 = new javax.swing.JButton();
        square_6_3 = new javax.swing.JButton();
        square_6_6 = new javax.swing.JButton();
        square_6_5 = new javax.swing.JButton();
        square_6_8 = new javax.swing.JButton();
        square_6_7 = new javax.swing.JButton();
        square_7_2 = new javax.swing.JButton();
        square_7_1 = new javax.swing.JButton();
        square_7_4 = new javax.swing.JButton();
        square_7_3 = new javax.swing.JButton();
        square_7_6 = new javax.swing.JButton();
        square_7_5 = new javax.swing.JButton();
        square_7_8 = new javax.swing.JButton();
        square_7_7 = new javax.swing.JButton();
        square_8_2 = new javax.swing.JButton();
        square_8_1 = new javax.swing.JButton();
        square_8_4 = new javax.swing.JButton();
        square_8_3 = new javax.swing.JButton();
        square_8_6 = new javax.swing.JButton();
        square_8_5 = new javax.swing.JButton();
        square_8_8 = new javax.swing.JButton();
        square_8_7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        square_1_2.setBackground(new java.awt.Color(153, 153, 153));
        square_1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_1_2ActionPerformed(evt);
            }
        });
        getContentPane().add(square_1_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 80, 80));

        square_1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_1_1ActionPerformed(evt);
            }
        });
        getContentPane().add(square_1_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 80));

        square_1_4.setBackground(new java.awt.Color(153, 153, 153));
        square_1_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_1_4ActionPerformed(evt);
            }
        });
        getContentPane().add(square_1_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 80, 80));

        square_1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_1_3ActionPerformed(evt);
            }
        });
        getContentPane().add(square_1_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 80, 80));

        square_1_6.setBackground(new java.awt.Color(153, 153, 153));
        square_1_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_1_6ActionPerformed(evt);
            }
        });
        getContentPane().add(square_1_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 80, 80));

        square_1_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_1_5ActionPerformed(evt);
            }
        });
        getContentPane().add(square_1_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 80, 80));

        square_1_8.setBackground(new java.awt.Color(153, 153, 153));
        square_1_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_1_8ActionPerformed(evt);
            }
        });
        getContentPane().add(square_1_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 80, 80));

        square_1_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_1_7ActionPerformed(evt);
            }
        });
        getContentPane().add(square_1_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 80, 80));

        square_2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_2_2ActionPerformed(evt);
            }
        });
        getContentPane().add(square_2_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 80, 80));

        square_2_1.setBackground(new java.awt.Color(153, 153, 153));
        square_2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_2_1ActionPerformed(evt);
            }
        });
        getContentPane().add(square_2_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 80, 80));

        square_2_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_2_4ActionPerformed(evt);
            }
        });
        getContentPane().add(square_2_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 80, 80));

        square_2_3.setBackground(new java.awt.Color(153, 153, 153));
        square_2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_2_3ActionPerformed(evt);
            }
        });
        getContentPane().add(square_2_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 80, 80));

        square_2_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_2_6ActionPerformed(evt);
            }
        });
        getContentPane().add(square_2_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 80, 80));

        square_2_5.setBackground(new java.awt.Color(153, 153, 153));
        square_2_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_2_5ActionPerformed(evt);
            }
        });
        getContentPane().add(square_2_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 80, 80));

        square_2_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_2_8ActionPerformed(evt);
            }
        });
        getContentPane().add(square_2_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 80, 80));

        square_2_7.setBackground(new java.awt.Color(153, 153, 153));
        square_2_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_2_7ActionPerformed(evt);
            }
        });
        getContentPane().add(square_2_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 80, 80));

        square_3_2.setBackground(new java.awt.Color(153, 153, 153));
        square_3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_3_2ActionPerformed(evt);
            }
        });
        getContentPane().add(square_3_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 80, 80));

        square_3_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_3_1ActionPerformed(evt);
            }
        });
        getContentPane().add(square_3_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 80, 80));

        square_3_4.setBackground(new java.awt.Color(153, 153, 153));
        square_3_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_3_4ActionPerformed(evt);
            }
        });
        getContentPane().add(square_3_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 80, 80));

        square_3_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_3_3ActionPerformed(evt);
            }
        });
        getContentPane().add(square_3_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 80, 80));

        square_3_6.setBackground(new java.awt.Color(153, 153, 153));
        square_3_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_3_6ActionPerformed(evt);
            }
        });
        getContentPane().add(square_3_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 80, 80));

        square_3_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_3_5ActionPerformed(evt);
            }
        });
        getContentPane().add(square_3_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 80, 80));

        square_3_8.setBackground(new java.awt.Color(153, 153, 153));
        square_3_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_3_8ActionPerformed(evt);
            }
        });
        getContentPane().add(square_3_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 80, 80));

        square_3_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_3_7ActionPerformed(evt);
            }
        });
        getContentPane().add(square_3_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 80, 80));

        square_4_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_4_2ActionPerformed(evt);
            }
        });
        getContentPane().add(square_4_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 80, 80));

        square_4_1.setBackground(new java.awt.Color(153, 153, 153));
        square_4_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_4_1ActionPerformed(evt);
            }
        });
        getContentPane().add(square_4_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 80, 80));

        square_4_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_4_4ActionPerformed(evt);
            }
        });
        getContentPane().add(square_4_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 80, 80));

        square_4_3.setBackground(new java.awt.Color(153, 153, 153));
        square_4_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_4_3ActionPerformed(evt);
            }
        });
        getContentPane().add(square_4_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 80, 80));

        square_4_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_4_6ActionPerformed(evt);
            }
        });
        getContentPane().add(square_4_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 80, 80));

        square_4_5.setBackground(new java.awt.Color(153, 153, 153));
        square_4_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_4_5ActionPerformed(evt);
            }
        });
        getContentPane().add(square_4_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 80, 80));

        square_4_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_4_8ActionPerformed(evt);
            }
        });
        getContentPane().add(square_4_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 80, 80));

        square_4_7.setBackground(new java.awt.Color(153, 153, 153));
        square_4_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_4_7ActionPerformed(evt);
            }
        });
        getContentPane().add(square_4_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 80, 80));

        square_5_2.setBackground(new java.awt.Color(153, 153, 153));
        square_5_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_5_2ActionPerformed(evt);
            }
        });
        getContentPane().add(square_5_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 80, 80));

        square_5_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_5_1ActionPerformed(evt);
            }
        });
        getContentPane().add(square_5_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 80, 80));

        square_5_4.setBackground(new java.awt.Color(153, 153, 153));
        square_5_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_5_4ActionPerformed(evt);
            }
        });
        getContentPane().add(square_5_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 80, 80));

        square_5_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_5_3ActionPerformed(evt);
            }
        });
        getContentPane().add(square_5_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 80, 80));

        square_5_6.setBackground(new java.awt.Color(153, 153, 153));
        square_5_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_5_6ActionPerformed(evt);
            }
        });
        getContentPane().add(square_5_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 80, 80));

        square_5_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_5_5ActionPerformed(evt);
            }
        });
        getContentPane().add(square_5_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 80, 80));

        square_5_8.setBackground(new java.awt.Color(153, 153, 153));
        square_5_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_5_8ActionPerformed(evt);
            }
        });
        getContentPane().add(square_5_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 80, 80));

        square_5_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_5_7ActionPerformed(evt);
            }
        });
        getContentPane().add(square_5_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 80, 80));

        square_6_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_6_2ActionPerformed(evt);
            }
        });
        getContentPane().add(square_6_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 80, 80));

        square_6_1.setBackground(new java.awt.Color(153, 153, 153));
        square_6_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_6_1ActionPerformed(evt);
            }
        });
        getContentPane().add(square_6_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 80, 80));

        square_6_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_6_4ActionPerformed(evt);
            }
        });
        getContentPane().add(square_6_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 80, 80));

        square_6_3.setBackground(new java.awt.Color(153, 153, 153));
        square_6_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_6_3ActionPerformed(evt);
            }
        });
        getContentPane().add(square_6_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 80, 80));

        square_6_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_6_6ActionPerformed(evt);
            }
        });
        getContentPane().add(square_6_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 80, 80));

        square_6_5.setBackground(new java.awt.Color(153, 153, 153));
        square_6_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_6_5ActionPerformed(evt);
            }
        });
        getContentPane().add(square_6_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 80, 80));

        square_6_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_6_8ActionPerformed(evt);
            }
        });
        getContentPane().add(square_6_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 80, 80));

        square_6_7.setBackground(new java.awt.Color(153, 153, 153));
        square_6_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_6_7ActionPerformed(evt);
            }
        });
        getContentPane().add(square_6_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 80, 80));

        square_7_2.setBackground(new java.awt.Color(153, 153, 153));
        square_7_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_7_2ActionPerformed(evt);
            }
        });
        getContentPane().add(square_7_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 80, 80));

        square_7_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_7_1ActionPerformed(evt);
            }
        });
        getContentPane().add(square_7_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 80, 80));

        square_7_4.setBackground(new java.awt.Color(153, 153, 153));
        square_7_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_7_4ActionPerformed(evt);
            }
        });
        getContentPane().add(square_7_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 80, 80));

        square_7_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_7_3ActionPerformed(evt);
            }
        });
        getContentPane().add(square_7_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 80, 80));

        square_7_6.setBackground(new java.awt.Color(153, 153, 153));
        square_7_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_7_6ActionPerformed(evt);
            }
        });
        getContentPane().add(square_7_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 80, 80));

        square_7_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_7_5ActionPerformed(evt);
            }
        });
        getContentPane().add(square_7_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 80, 80));

        square_7_8.setBackground(new java.awt.Color(153, 153, 153));
        square_7_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_7_8ActionPerformed(evt);
            }
        });
        getContentPane().add(square_7_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 80, 80));

        square_7_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_7_7ActionPerformed(evt);
            }
        });
        getContentPane().add(square_7_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 80, 80));

        square_8_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_8_2ActionPerformed(evt);
            }
        });
        getContentPane().add(square_8_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 80, 80));

        square_8_1.setBackground(new java.awt.Color(153, 153, 153));
        square_8_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_8_1ActionPerformed(evt);
            }
        });
        getContentPane().add(square_8_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 80, 80));

        square_8_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_8_4ActionPerformed(evt);
            }
        });
        getContentPane().add(square_8_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 80, 80));

        square_8_3.setBackground(new java.awt.Color(153, 153, 153));
        square_8_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_8_3ActionPerformed(evt);
            }
        });
        getContentPane().add(square_8_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, 80, 80));

        square_8_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_8_6ActionPerformed(evt);
            }
        });
        getContentPane().add(square_8_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 560, 80, 80));

        square_8_5.setBackground(new java.awt.Color(153, 153, 153));
        square_8_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_8_5ActionPerformed(evt);
            }
        });
        getContentPane().add(square_8_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, 80, 80));

        square_8_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_8_8ActionPerformed(evt);
            }
        });
        getContentPane().add(square_8_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, 80, 80));

        square_8_7.setBackground(new java.awt.Color(153, 153, 153));
        square_8_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square_8_7ActionPerformed(evt);
            }
        });
        getContentPane().add(square_8_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 80, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void square_1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_1_3ActionPerformed
        show_moves(1, 3);
    }//GEN-LAST:event_square_1_3ActionPerformed

    private void square_1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_1_1ActionPerformed
        show_moves(1, 1);
    }//GEN-LAST:event_square_1_1ActionPerformed

    private void square_1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_1_2ActionPerformed
        show_moves(1, 2);
    }//GEN-LAST:event_square_1_2ActionPerformed

    private void square_1_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_1_4ActionPerformed
        show_moves(1, 4);
    }//GEN-LAST:event_square_1_4ActionPerformed

    private void square_1_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_1_5ActionPerformed
       show_moves(1, 5);
    }//GEN-LAST:event_square_1_5ActionPerformed

    private void square_1_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_1_8ActionPerformed
        show_moves(1,8);
    }//GEN-LAST:event_square_1_8ActionPerformed

    private void square_1_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_1_7ActionPerformed
        show_moves(1, 7);
    }//GEN-LAST:event_square_1_7ActionPerformed

    private void square_1_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_1_6ActionPerformed
       show_moves(1, 6);
    }//GEN-LAST:event_square_1_6ActionPerformed

    private void square_2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_2_2ActionPerformed
       show_moves(2, 2);
    }//GEN-LAST:event_square_2_2ActionPerformed

    private void square_2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_2_1ActionPerformed
        show_moves(2, 1);
    }//GEN-LAST:event_square_2_1ActionPerformed

    private void square_2_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_2_4ActionPerformed
       show_moves(2, 4);
    }//GEN-LAST:event_square_2_4ActionPerformed

    private void square_2_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_2_3ActionPerformed
       show_moves(2, 3);
    }//GEN-LAST:event_square_2_3ActionPerformed

    private void square_2_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_2_6ActionPerformed
       show_moves(2, 6);
    }//GEN-LAST:event_square_2_6ActionPerformed

    private void square_2_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_2_5ActionPerformed
       show_moves(2, 5);
    }//GEN-LAST:event_square_2_5ActionPerformed

    private void square_2_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_2_8ActionPerformed
       show_moves(2, 8);
    }//GEN-LAST:event_square_2_8ActionPerformed

    private void square_2_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_2_7ActionPerformed
       show_moves(2, 7);
    }//GEN-LAST:event_square_2_7ActionPerformed

    private void square_3_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_3_2ActionPerformed
      show_moves(3, 2);
    }//GEN-LAST:event_square_3_2ActionPerformed

    private void square_3_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_3_1ActionPerformed
        show_moves(3, 1);
    }//GEN-LAST:event_square_3_1ActionPerformed

    private void square_3_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_3_4ActionPerformed
       show_moves(3, 4);
    }//GEN-LAST:event_square_3_4ActionPerformed

    private void square_3_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_3_3ActionPerformed
        show_moves(3, 3);
    }//GEN-LAST:event_square_3_3ActionPerformed

    private void square_3_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_3_6ActionPerformed
        show_moves(3, 6);
    }//GEN-LAST:event_square_3_6ActionPerformed

    private void square_3_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_3_5ActionPerformed
        show_moves(3, 5);
    }//GEN-LAST:event_square_3_5ActionPerformed

    private void square_3_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_3_8ActionPerformed
        show_moves(3, 8);
    }//GEN-LAST:event_square_3_8ActionPerformed

    private void square_3_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_3_7ActionPerformed
        show_moves(3, 7);
    }//GEN-LAST:event_square_3_7ActionPerformed

    private void square_4_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_4_2ActionPerformed
        show_moves(4, 2);
    }//GEN-LAST:event_square_4_2ActionPerformed

    private void square_4_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_4_1ActionPerformed
        show_moves(4, 1);
    }//GEN-LAST:event_square_4_1ActionPerformed

    private void square_4_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_4_4ActionPerformed
        show_moves(4, 4);
    }//GEN-LAST:event_square_4_4ActionPerformed

    private void square_4_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_4_3ActionPerformed
        show_moves(4, 3);
    }//GEN-LAST:event_square_4_3ActionPerformed

    private void square_4_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_4_6ActionPerformed
        show_moves(4, 6);
    }//GEN-LAST:event_square_4_6ActionPerformed

    private void square_4_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_4_5ActionPerformed
        show_moves(4, 5);
    }//GEN-LAST:event_square_4_5ActionPerformed

    private void square_4_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_4_8ActionPerformed
        show_moves(4, 8);
    }//GEN-LAST:event_square_4_8ActionPerformed

    private void square_4_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_4_7ActionPerformed
        show_moves(4, 7);
    }//GEN-LAST:event_square_4_7ActionPerformed

    private void square_5_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_5_2ActionPerformed
        show_moves(5,2);
    }//GEN-LAST:event_square_5_2ActionPerformed

    private void square_5_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_5_1ActionPerformed
       show_moves(5, 1);
    }//GEN-LAST:event_square_5_1ActionPerformed

    private void square_5_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_5_4ActionPerformed
        show_moves(5, 4);
    }//GEN-LAST:event_square_5_4ActionPerformed

    private void square_5_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_5_3ActionPerformed
        show_moves(5, 3);
    }//GEN-LAST:event_square_5_3ActionPerformed

    private void square_5_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_5_6ActionPerformed
        show_moves(5, 6);
    }//GEN-LAST:event_square_5_6ActionPerformed

    private void square_5_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_5_5ActionPerformed
        show_moves(5, 5);
    }//GEN-LAST:event_square_5_5ActionPerformed

    private void square_5_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_5_8ActionPerformed
        show_moves(5, 8);
    }//GEN-LAST:event_square_5_8ActionPerformed

    private void square_5_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_5_7ActionPerformed
        show_moves(5, 7);
    }//GEN-LAST:event_square_5_7ActionPerformed

    private void square_6_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_6_2ActionPerformed
        show_moves(6, 2);
    }//GEN-LAST:event_square_6_2ActionPerformed

    private void square_6_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_6_1ActionPerformed
        show_moves(6, 1);
    }//GEN-LAST:event_square_6_1ActionPerformed

    private void square_6_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_6_4ActionPerformed
        show_moves(6, 4);
    }//GEN-LAST:event_square_6_4ActionPerformed

    private void square_6_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_6_3ActionPerformed
       show_moves(6, 3);
    }//GEN-LAST:event_square_6_3ActionPerformed

    private void square_6_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_6_6ActionPerformed
        show_moves(6, 6);
    }//GEN-LAST:event_square_6_6ActionPerformed

    private void square_6_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_6_5ActionPerformed
       show_moves(6, 5);
    }//GEN-LAST:event_square_6_5ActionPerformed

    private void square_6_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_6_8ActionPerformed
       show_moves(6, 8);
    }//GEN-LAST:event_square_6_8ActionPerformed

    private void square_6_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_6_7ActionPerformed
        show_moves(6, 7);
    }//GEN-LAST:event_square_6_7ActionPerformed

    private void square_7_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_7_2ActionPerformed
        show_moves(7, 2);
    }//GEN-LAST:event_square_7_2ActionPerformed

    private void square_7_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_7_1ActionPerformed
        show_moves(7, 1);
    }//GEN-LAST:event_square_7_1ActionPerformed

    private void square_7_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_7_4ActionPerformed
        show_moves(7, 4);
    }//GEN-LAST:event_square_7_4ActionPerformed

    private void square_7_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_7_3ActionPerformed
       show_moves(7, 3);
    }//GEN-LAST:event_square_7_3ActionPerformed

    private void square_7_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_7_6ActionPerformed
        show_moves(7, 6);
    }//GEN-LAST:event_square_7_6ActionPerformed

    private void square_7_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_7_5ActionPerformed
        show_moves(7, 5);
    }//GEN-LAST:event_square_7_5ActionPerformed

    private void square_7_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_7_8ActionPerformed
       show_moves(7, 8);
    }//GEN-LAST:event_square_7_8ActionPerformed

    private void square_7_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_7_7ActionPerformed
        show_moves(7, 7);
    }//GEN-LAST:event_square_7_7ActionPerformed

    private void square_8_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_8_2ActionPerformed
       show_moves(8, 2);
    }//GEN-LAST:event_square_8_2ActionPerformed

    private void square_8_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_8_1ActionPerformed
       show_moves(8, 1);
    }//GEN-LAST:event_square_8_1ActionPerformed

    private void square_8_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_8_4ActionPerformed
        show_moves(8, 4);
    }//GEN-LAST:event_square_8_4ActionPerformed

    private void square_8_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_8_3ActionPerformed
        show_moves(8, 3);
    }//GEN-LAST:event_square_8_3ActionPerformed

    private void square_8_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_8_6ActionPerformed
       show_moves(8, 6);
    }//GEN-LAST:event_square_8_6ActionPerformed

    private void square_8_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_8_5ActionPerformed
        show_moves(8, 5);
    }//GEN-LAST:event_square_8_5ActionPerformed

    private void square_8_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_8_8ActionPerformed
        show_moves(8, 8);
    }//GEN-LAST:event_square_8_8ActionPerformed

    private void square_8_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square_8_7ActionPerformed
        show_moves(8, 7);
    }//GEN-LAST:event_square_8_7ActionPerformed

    /**
     * @param args the command line arguments
     */
    
      
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton square_1_1;
    private javax.swing.JButton square_1_2;
    private javax.swing.JButton square_1_3;
    private javax.swing.JButton square_1_4;
    private javax.swing.JButton square_1_5;
    private javax.swing.JButton square_1_6;
    private javax.swing.JButton square_1_7;
    private javax.swing.JButton square_1_8;
    private javax.swing.JButton square_2_1;
    private javax.swing.JButton square_2_2;
    private javax.swing.JButton square_2_3;
    private javax.swing.JButton square_2_4;
    private javax.swing.JButton square_2_5;
    private javax.swing.JButton square_2_6;
    private javax.swing.JButton square_2_7;
    private javax.swing.JButton square_2_8;
    private javax.swing.JButton square_3_1;
    private javax.swing.JButton square_3_2;
    private javax.swing.JButton square_3_3;
    private javax.swing.JButton square_3_4;
    private javax.swing.JButton square_3_5;
    private javax.swing.JButton square_3_6;
    private javax.swing.JButton square_3_7;
    private javax.swing.JButton square_3_8;
    private javax.swing.JButton square_4_1;
    private javax.swing.JButton square_4_2;
    private javax.swing.JButton square_4_3;
    private javax.swing.JButton square_4_4;
    private javax.swing.JButton square_4_5;
    private javax.swing.JButton square_4_6;
    private javax.swing.JButton square_4_7;
    private javax.swing.JButton square_4_8;
    private javax.swing.JButton square_5_1;
    private javax.swing.JButton square_5_2;
    private javax.swing.JButton square_5_3;
    private javax.swing.JButton square_5_4;
    private javax.swing.JButton square_5_5;
    private javax.swing.JButton square_5_6;
    private javax.swing.JButton square_5_7;
    private javax.swing.JButton square_5_8;
    private javax.swing.JButton square_6_1;
    private javax.swing.JButton square_6_2;
    private javax.swing.JButton square_6_3;
    private javax.swing.JButton square_6_4;
    private javax.swing.JButton square_6_5;
    private javax.swing.JButton square_6_6;
    private javax.swing.JButton square_6_7;
    private javax.swing.JButton square_6_8;
    private javax.swing.JButton square_7_1;
    private javax.swing.JButton square_7_2;
    private javax.swing.JButton square_7_3;
    private javax.swing.JButton square_7_4;
    private javax.swing.JButton square_7_5;
    private javax.swing.JButton square_7_6;
    private javax.swing.JButton square_7_7;
    private javax.swing.JButton square_7_8;
    private javax.swing.JButton square_8_1;
    private javax.swing.JButton square_8_2;
    private javax.swing.JButton square_8_3;
    private javax.swing.JButton square_8_4;
    private javax.swing.JButton square_8_5;
    private javax.swing.JButton square_8_6;
    private javax.swing.JButton square_8_7;
    private javax.swing.JButton square_8_8;
    // End of variables declaration//GEN-END:variables
    
    
}
